export const ROLES_CONSTANT = {
  ADMIN: "ADMIN",
  SUBADMIN: "SUBADMIN",
  // USER: "USER",
  MANUFACTURER: "MANUFACTURER/IMPORTER",
  DISTRIBUTOR: "DISTRIBUTOR",
  DEALER: "DEALER",
  FIELDUSER: "FIELDUSER",
  APPROVERS: "APPROVERS",
  SALES: "SALES"

}

export const APPROVED_STATUS = {
  APPROVED: "APPROVED",
  PENDING: "PENDING",
  REJECTED: "REJECTED"
}
